apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  # Database
  POSTGRES_HOST: "{{ .Release.Name }}-postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_DB: "{{ .Values.postgres.db }}"
  
  # Event Bus
  RABBITMQ_URL: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.password }}@{{ .Release.Name }}-rabbitmq:5672/"
  
  # Object Storage
  S3_ENDPOINT: "http://{{ .Release.Name }}-minio:9000"
  S3_BUCKET: "{{ .Values.env.s3Bucket }}"
  S3_ACCESS_KEY: "{{ .Values.minio.accessKey }}"
  S3_SECRET_KEY: "{{ .Values.minio.secretKey }}"
